### ISSUE TITLE
README example no longer works

### ISSUE THREAD

**Issue by din0s** [metamodules/mongo#3]
I am trying to use this metamodule along with `create-node-app` and when I use the example code in README I get the following error:

```
[api] var kittySchema = new mongo.Schema({
[api]                   ^
[api] 
[api] TypeError: mongo.Schema is not a constructor
[api]     at Object.<anonymous> (/tmp/mongo/src/api/index.js:8:19)
[api]     at Module._compile (internal/modules/cjs/loader.js:1151:30)
[api]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
[api]     at Module.load (internal/modules/cjs/loader.js:1000:32)
[api]     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[api]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[api]     at internal/main/run_main_module.js:17:47
```
After experimenting, I've found that changing the following line seems to fix the issue.
```diff
- const mongo = require("@metamodules/mongo")()
+ const mongo = require("@metamodules/mongo")().base
```

Hope this is helpful to you!

**Comment by pastudan** [comment]
Thank you for your feedback! I've updated the README to reflect this change.
